FrontBundle\Entity\Charge:
    type: entity
    table: null
    repositoryClass: FrontBundle\Repository\ChargeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        titre:
            type: string
            length: 255
            unique: true
        montant:
            type: integer
        dateEcheance:
            type: datetime
            column: date_echeance
        statut:
            type: boolean
        user:
            type: array

    oneToOne:
        contrat:
          targetEntity: FrontBundle\Entity\Contrat
          cascade: ["persist","remove"]
          joinColumn:
            name: contrat_id
            referencedColumnName: id
            onDelete: CASCADE
        piecejointe:
          targetEntity: FrontBundle\Entity\Piecejointe
          cascade: ["persist","remove"]
          joinColumn:
            name: piecejointe_id
            referencedColumnName: id
            onDelete: CASCADE

    oneToMany:
        versements:
          targetEntity: FrontBundle\Entity\Versement
          mappedBy: charge
          cascade: ["persist","merge"]

    manyToMany:
        users:
          targetEntity: UserBundle\Entity\User
          joinTable:
             name: charges_users
             joinColumns:
               charge_id:
                 referencedColumnName: id
             inverseJoinColumns:
               user_id:
                 referencedColumnName: id



    lifecycleCallbacks: {  }
