FrontBundle\Entity\FileMessages:
    type: entity
    table: null
    repositoryClass: FrontBundle\Repository\FileMessagesRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        titre:
            type: string
            length: 255
            unique: true
        etat:
            type: boolean
        dateDebut:
            type: datetime
            column: date_debut
        dateFin:
            type: datetime
            nullable: true
            column: date_fin
        idUser:
            type: string
            length: 255
            nullable: true
            column: id_user

    oneToMany:
        messages:
          targetEntity: FrontBundle\Entity\Message
          mappedBy: filemessage
          cascade: ["persist", "merge"]


    manyToMany:
        users:
          targetEntity: UserBundle\Entity\User
          joinTable:
             name: filemessages_users
             joinColumns:
               filemessages_id:
                 referencedColumnName: id
             inverseJoinColumns:
               user_id:
                 referencedColumnName: id


    lifecycleCallbacks: {  }
