FrontBundle\Entity\Piecejointe:
    type: entity
    table: null
    repositoryClass: FrontBundle\Repository\PiecejointeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:

        url:
            type: string
            length: 255
            nullable: false
        alt:
            type: string
            length: 255
            nullable: true

    lifecycleCallbacks:
     prePersist: [ preUpload ]
     preUpdate: [ preUpload ]
     postPersist: [ upload ]
     postUpdate: [ upload ]
     preRemove: [ preRemoveUpload ]
     postRemove: [ removeUpload ]


