user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /

back:
    resource: "@BackBundle/Resources/config/routing.yml"
    prefix:   /

front:
    resource: "@FrontBundle/Resources/config/routing.yml"
    prefix:   /

login: #kcdev
    path: /login
    defaults:
        _controller: UserBundle:Security:login

login_check: #kcdev
    path: /login_check

logout:
    path: /logout

app:
    resource: '@AppBundle/Controller/'
    type: annotation
