back:
    resource: "@BackBundle/Controller/"
    type: annotation
    prefix:   /back

front:
    resource: "@FrontBundle/Controller/"
    type: annotation
    prefix:   /front


app:
    resource: '@AppBundle/Controller/'
    type: annotation
    prefix:   /
