UserBundle\Entity\User:
    type: entity
    table: null
    repositoryClass: UserBundle\Repository\UserRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        telephone:
            type: integer

        adresse:
            type: string
            length: 255

oneToMany:
    notifications:
      targetEntity: FrontBundle\Entity\Notification
      mappedBy: user
      cascade: ["persist", "merge"]
