<?php

namespace FrontBundle\Repository;

/**
 * FileMessagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FileMessagesRepository extends \Doctrine\ORM\EntityRepository
{
}
