<?php

namespace FrontBundle\Repository;

/**
 * PiecejointeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PiecejointeRepository extends \Doctrine\ORM\EntityRepository
{
}
