<?php

namespace FrontBundle\Repository;

/**
 * PjointeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PjointeRepository extends \Doctrine\ORM\EntityRepository
{
}
